### PR TITLE
Update registration exercises

### LINKED ISSUE #6: Update Registration
- [x] Exercises [use %load](https://github.com/glemaitre/pyparis-2018-sklearn/blob/master/notebook.ipynb)
- [x] Add another registration example
- [x] Make sure that there is a good explanation for backward vs forward transform
- [x] Update cell 4 to point to updated slides

### PR DESCRIPTION
**Pull request by dzenanz**
Closes #6.

### CODE REVIEW

**Comment by thewtex** [comment]
The optimizer scales can be set with, e.g.

```
scales = itk.OptimizerParameters[itk.D](initial_transform.GetNumberOfParameters())
translation_scale = 1.0 / 1000
scales.SetElement(0, 1.0)
scales.SetElement(1, translation_scale)
scales.SetElement(2, translation_scale)

optimizer = itk.GradientDescentOptimizerv4Template.New(
        Scales=scales,
        ReturnBestParametersAndValue=True,
        NumberOfIterations=200)
```

We do not have automatic conversion of a Python list to `itk.OptimizerParameters`, yet ... ;-).

We may want to use the best practice of a scales estimator here.

**Comment by dzenanz** [comment]
I think this data is too challenging. I couldn't even get Slicer to register this! Should I abandon this example, or try to find easier inputs?

**Comment by thewtex** [comment]
How about easier inputs?

**Comment by dzenanz** [comment]
This PR is now ready for reviewing/merging 😫

**Comment by thewtex** [comment]
Tested locally. Awesome work @dzenanz ! :100: :1st_place_medal:

**Pull request merged**
